### ISSUE TITLE
unable to add image assets

### ISSUE THREAD

**Issue by raghavd17** [maoberlehner/setting-up-a-vue-project-with-webpack-4-and-babel-7#1]
Hi,

When I add any image assets in any of the components I am not getting that component in the landing page.

I have added the configuration with the following instructions 
https://webpack.js.org/guides/asset-management/#loading-images
 still, I am getting errors saying file not found. 
I have cross checked the file path as well.

![image](https://user-images.githubusercontent.com/1301624/42930041-861b5648-8b59-11e8-9f5e-41eaba6cbc84.png)

**Comment by maoberlehner** [comment]
Hi @raghavd17,

you have to add the configuration for that. You can take a look at the official webpack documentation for more informations: https://webpack.js.org/guides/asset-management/#loading-images
