### ISSUE TITLE
Hot Module Reloading seems not working

### ISSUE THREAD

**Issue by kevguy** [maoberlehner/setting-up-a-vue-project-with-webpack-4-and-babel-7#3]
It seems like any changes to the vue files are not reflected in development mode. All I did was clone your code and did a `yarn install`. Then I tried explicitly setting `hotReload` to be `true` in `webpack.config.js`, and it's still not working.

```
{
    test: /\.vue$/,
    loader: `vue-loader`,
    options: {
      hotReload: true,
    }
},
```

**Comment by maoberlehner** [comment]
Hey @kevguy!

I just checked it running the following steps, hot reload does work without any problems:

```bash
git clone git@github.com:maoberlehner/setting-up-a-vue-project-with-webpack-4-and-babel-7.git
cd setting-up-a-vue-project-with-webpack-4-and-babel-7
npm install
npm start
```

There might be a problem with new versions of some npm packages. Thats why I've added a `package-lock.json` file. Using yarn might lead to installing (newer) incompatible versions of some packages.

I write one article every week (and earning 0 € doing so). I hope you understand, that it would be impossible for me to maintain all of my example projects and update their npm dependencies. But I'd gladly accept a working pull request with updated dependencies ;)

That said, my article was written before Vue CLI 3.0 was released. Vue CLI 3.0 uses webpack 4 and Babel 7 internally. I highly recommend everybody to use Vue CLI 3.0 when starting a new project. So this repository and the corresponding article are kinda obsolete anyway in my opinion.

Thanks for taking the time reading my article and checking out this repository!

**Comment by kevguy** [comment]
Thank you so much. I'll give it a try again and think about it some more. The HMR doesn't work on my laptop which is running Ubuntu, but it somehow works on my Chromebook (I installed a Ubuntu in it). 

I really appreciate your work on this one. Vue CLI 3.0 is really convenient and it lacks an eject feature (I know `vue.config.js`, I had some time working with it) so I wanted to have a webpack config where I can make changes myself instead. A while ago I was building this website (https://borecast.com) with Webpack 4 based on the configs from Vue's HackerNews example app (which is still using Webpack 3). The migration took me 3 days. And this two days I was doing some hobby project but I feel like the configs I used is a bit of an overkill cuz I don't need SSR and I always want to puke when I have to write Webpack configs, so I'd been trying to find something simpler and I came across your blog posts. I'm actually using your templates now tbh, you really saved me a lot of time, so thank you so much for all the work!

**Comment by maoberlehner** [comment]
Thank you for your kind words! I'm glad that my article was still useful for you although HMR does not work as expected. If you find a solution to the problem I'd be happy to update this repository and my article so it may be helpful to others facing the same issues. Thanks!
